### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by Twist00** [QuentinCaffeino/godot-console#1]
when copying the project and testing it this shows up

Invalid call. Nonexistent function 'register' in base 'Nil'

im new to Godot so i dont know what im doing wrong

**Comment by QuentinCaffeino** [comment]
Hello,

Have you followed installation step-by-step?
https://github.com/QuentinCaffeino/godot-console#installation

Good day :smiley:

**Comment by GameingTwist** [comment]
Did all the installation before reporting the issue

**Comment by QuentinCaffeino** [comment]
Could you please show me your `project.godot`. It should be in root game directory.
