### ISSUE TITLE
 indented block expected

### ISSUE THREAD

**Issue by dijam8** [QuentinCaffeino/godot-console#10]
this is my error : 
![Screenshot from 2019-07-01 23-29-21](https://user-images.githubusercontent.com/50689412/60470364-1c751100-9c58-11e9-9076-b746f1b4f12a.png)

**Comment by QuentinCaffeino** [comment]
Hello,
have you found the error already?

**Comment by dijam8** [comment]
the error is : indented block expected in the line number 5.
but i do not know why

**Comment by DmDerbin** [comment]
func f():
    pass

**Comment by dijam8** [comment]
thanks

**Comment by dijam8** [comment]
but it did not work

**Comment by dijam8** [comment]
ok i solve it by reconnecting the signal
