### ISSUE TITLE
Using a FuncRef in add_command raises an error

### ISSUE THREAD

**Issue by PraxTube** [quentincaffeino/godot-console#105]
Godot Version: **3.5.1**
Godot-Console Version: **Develop** #102 (is this the recommended branch to use? Couldn't find any stable/recommended branches)

When trying to use `funcref` in the `add_command` function I get the following error.

`Invalid call. Nonexistent function 'set_name' in base 'Reference (FuncRefCallbackBuilder.gd)'.`

in `CommandBuilder.gd:53`

**How to reproduce:**

```gdscript
# Function that will be called by our command
func print_hello(name = ''):
	Console.write_line('Hello ' + name + '!')

func _ready():
	# Registering command
	# 1. argument is command name
	# 2. arg. is target (target could be a funcref)
	# 3. arg. is target name (name is not required if it is the same as first arg or target is a funcref)
	Console.add_command('sayHello', funcref(self, "print_hello"))\
		.set_description('Prints "Hello %name%!"')\
		.add_argument('name', TYPE_STRING)\
		.register()
```

**Comment by quentincaffeino** [comment]
Currently yes, develop is a main branch, I will change that later to more appropriate main. 

I messed it up during refactoring, as a hotfix if you plan to use only funcrefs please comment this line in your project: 

https://github.com/quentincaffeino/godot-console/blob/develop/addons/quentincaffeino/console/src/Command/CommandBuilder.gd#L54

I will try to make a proper fix later this day

**Comment by quentincaffeino** [comment]
@all-contributors please add @PraxTube for bug
