### ISSUE TITLE
Run in Web Editor?

### ISSUE THREAD

**Issue by pjburnhill** [quentincaffeino/godot-console#109]
I'm trying to help my son to run Godot via the Web Editor, is there an easy way to import/run the console into that environment as there is no AssetLib?

You can't seem to import a whole folder structure in Web Editor, just the files. So if I use the packaged master, I'd have to manually create the whole folder structure in the editor assets panel.

I assume it couldn't be loaded directly from github with something like jsdelivr (at runtime?)? Would that cause CORS issues?

**Comment by pjburnhill** [comment]
To answer my own question. The issue was that the `demo-csharp` project, which is added to `res://` by the plugin was being imported into the Web Editor, not the main project. By removing the `demo-csharp` project in the native editor and then zipping the project, it works fine.

**Comment by quentincaffeino** [comment]
Hi, @pjburnhill. Glad you found a solution, hope your son will enjoy learning godot!

**Comment by quentincaffeino** [comment]
I will check the mentioned case with demo, in case I find an easier way to do it I'll share it with you

**Comment by quentincaffeino** [comment]
@pjburnhill  You might be also interested in: https://github.com/GDQuest/learn-gdscript
