### ISSUE TITLE
Fix for 3.1

### ISSUE THREAD

**Issue by paulhocker** [QuentinCaffeino/godot-console#12]
I was able to get this functioning i 3.1 but in order to do it I needed to basically remove all of those __init__ scripts that you have. 

I did not fully understand how they were being used. 

I would think that many of the objects that you have created need to be converted into GDS classes now so that they are registered globally.

I did not make a pull request because I was not sure what your approach to fixing this is.

**Comment by paulhocker** [comment]
I did use the DEV branch. I also noticed that there are a couple of PR's in the queue so I was not sure what you were doing with those as well.

I would love to help where I can.

**Comment by QuentinCaffeino** [comment]
PRs are mostly outdated, they were submitted at the same time I was doing same fixes myself. So I do plan to review them once again and maybe merge some code from them.

Right now I don't have that much time to spend on this project. So mostly it works like this: I get an issue, I fix it, add some more stuff. Maybe rewrite some code I don't like, first version was written so it just works.

I'll have a look at project state when I'll be at home. Do you use Discord, Telegram or ...? We can add each other so connection is smoother and faster.
Best.

**Comment by QuentinCaffeino** [comment]
So I took a look at the project and was astonished. I made several dozen changes and and forgot about them. I'll review them if they are at least something close to ready and push them soon.

**Comment by jknightdoeswork** [comment]
I cant get this to work in 3.1.

Right now I'm seeing line 22 on CommandBuilder.gd saying "Identifier Callback is not declared in the current scope".

**Comment by QuentinCaffeino** [comment]
It should be all fixed. Closing for now.
