### ISSUE TITLE
CommandBuilder.buildDeprecated does not exist

### ISSUE THREAD

**Issue by danilw** [QuentinCaffeino/godot-console#13]
thanks for very useful addon!

small typo 

https://github.com/QuentinCaffeino/godot-console/blob/dev/src/Command/CommandGroup.gd#L85
`var command = CommandBuilder.buildDeprecated(lastNamePart, parameters)  # Command|int`

changing `buildDeprecated` to `build` make it work

**Comment by QuentinCaffeino** [comment]
Glad to hear that!
Thanks for reporting, fixed)
