### ISSUE TITLE
Autocomplete on TAB not working

### ISSUE THREAD

**Issue by aganm** [quentincaffeino/godot-console#14]
If I type any letters and press TAB, nothing happens.

Using Godot 3.1.2

**Comment by aganm** [comment]
I don't know if this is related, but when I activate the plugin, I get errors:
`
 Resource: 'res://addons/quentincaffeino-console/src/Console.tscn' is already being loaded. Cyclic reference?
 res://addons/quentincaffeino-console/src/Misc/BaseCommands.gd:54 - Parse Error: Identifier 'Console' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/quentincaffeino-console/src/Console.gd:4 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 Resource: 'res://addons/quentincaffeino-console/src/Console.tscn' is already being loaded. Cyclic reference?
 Resource: 'res://addons/quentincaffeino-console/src/Console.tscn' is already being loaded. Cyclic reference?
 Resource: 'res://addons/quentincaffeino-console/src/Console.tscn' is already being loaded. Cyclic reference?
 Resource: 'res://addons/quentincaffeino-console/src/Console.tscn' is already being loaded. Cyclic reference?
 res://addons/quentincaffeino-console/src/ConsoleLine.gd:37 - Parse Error: Identifier 'Console' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/quentincaffeino-console/src/Misc/BaseCommands.gd:54 - Parse Error: Identifier 'Console' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
`

**Comment by QuentinCaffeino** [comment]
Hello, thanks for reporting.
I'm aware of this behavior, rn it doesn't work, should have removed it from readme. In the nearest future I won't have time to fix this.

**Comment by quentincaffeino** [comment]
Now with new release it's fixed, console would autocomplete if there's only one command starting with what user typed, eg.: e -> echo, co -> commands. But with h, it will write out both available options which is help and history. At the moment it wont autocomplete if there's more than one command found, but I an planning to add this in the future.

I'm going to close this issue because I'm considering this as resolved, if you would have any other issue don't hesitate to open new ussue.
