### ISSUE TITLE
Autocomplete on ENTER works only once 

### ISSUE THREAD

**Issue by aganm** [quentincaffeino/godot-console#15]
For example, I type 'comm', press ENTER. It executes the command 'commands'.
If I type 'comm' again, press ENTER, I get :
`[ERROR] CommandGroup: _getCommand: Unable to provide with proper autocomplete.`

This goes for any command. Does a first ENTER will work, then any subsequent try gives the error above.

Using Godot 3.1.2

**Comment by QuentinCaffeino** [comment]
This is a bug, I'll take a look as soon as possible. Thx)
