### ISSUE TITLE
mixing space and tab in godot 3.2 b4

### ISSUE THREAD

**Issue by hpn33** [QuentinCaffeino/godot-console#16]
godot automatic make four space to one tab.
so script not working.

**Comment by QuentinCaffeino** [comment]
Accidentally closed the issue. Could you please provide more information about the issue. Some examples of things you were typing in to the console?

**Comment by hpn33** [comment]
no console.
plugin script it changed by engine.

# i install plugin 
- and active that
- and put console instance on my scene 
- and set input map

all thing that should be do, i do but 
some four space of your code changed to one tab
and preload's have some error 'could not fully preload the script'
and ... !!!
actually i don't know more 

> please make a project that console work on
> This way I better understand what to do

**Comment by QuentinCaffeino** [comment]
Ok, then easiest thing would be to reinstall console and don't open its code with engine editor so it wouldn't mess up the code.
I have example project locally but sadly it isn't any where close to finishing so I'm not planning to upload it in any near future.

**Comment by hpn33** [comment]
it worked that way 
- release a simple example project for this plugin, please.
this code problem itself is an issue that should be fix. ( you wanna i open that? o_o)
thanks for your help.

**Comment by kimamb** [comment]
This is a really annoying issue. Because if anything errors in the console, Godot opens the script and it's ruined.

**Comment by QuentinCaffeino** [comment]
@kimamb I agree that this is actually an issue, and there is already a [issue on godot for that](https://github.com/godotengine/godot/issues/35007).
What is the default indentation for godot, guess I could convert to it.

**Comment by kimamb** [comment]
The default indentation is tabs. There has to be some software out there (or some unix command) to convert between the two.

**Comment by QuentinCaffeino** [comment]
Pushed commit. For now you can now update from this branch.
