### ISSUE TITLE
Behavior: Clear text when hitting enter even if not valid command

### ISSUE THREAD

**Issue by MJBrune** [quentincaffeino/godot-console#18]
So if you type an invalid command and hit enter the invalid command sticks around.

From my experience (warning: anecdotal) hitting enter should clear the invalid command but add it to the history. If you want to recall the command you'd hit up and adjust it.

As this behavior can be created in 2 line changes in ConsoleLine.gd (091-092) I'd think that this is instead by design? Perhaps some sort of plugin option might be best if it's conflicting design with defacto standard?

Thanks,
Michael Brune

**Comment by QuentinCaffeino** [comment]
While developing this console I actually was trying to achieve the linux shell-like behavior, but this thing somehow slipped out of my field of view.
So I would change the current behavior.

Thanks,
Sergei ZH
