### ISSUE TITLE
Behaviour: Tab should autocomplete commands in history.

### ISSUE THREAD

**Issue by MJBrune** [quentincaffeino/godot-console#19]
As a lot of the time commands can autocomplete to different commands it's been common in Bash and other linux command lines to have tab autocomplete to the next option.

if you have commands 'hef', 'hel' and 'help' then h-<tab> displays hef as it's the shortest and closest match. <tab> again (after completed to hef) autocompletes to hel then <tab> one last time autocompletes to help.

This can be done by holding the original typed string in a buffer (variable or such) and then iterating over the original list of autocompleted options. Typing again would clear this buffer and option list.

Thanks,
Michael Brune

**Comment by quentincaffeino** [comment]
It is fixed with the new release, I've written more in [this comment](https://github.com/quentincaffeino/godot-console/issues/14#issuecomment-564904786).

Please feel free to reopen this issue if you would find any problems with this.
