### ISSUE TITLE
Parser Error: Expected Indent block after 'if'

### ISSUE THREAD

**Issue by paulhocker** [QuentinCaffeino/godot-console#2]
It's possible this is my problem, but I am receiving this error in Console.gd. Reviewing it, the code indent blocks look messed up, they are two spaces instead of the traditional four. I don't think that is the problem though, it looks like some tabs are missing? At any rate, this causes the code to error out. Any suggestions?

![image](https://user-images.githubusercontent.com/2214652/44946824-2a080300-adc9-11e8-9483-23dac90f401c.png)

**Comment by QuentinCaffeino** [comment]
Yeah, I'm using two spaces margin but this shouldn't be the problem.
Could you please tell me the version of godot that you are using?

**Comment by paulhocker** [comment]
I am using 3.0.6.stable.official.8314054.

I have also tried it in lower versions too. I am running Windows 10 - not sure that makes much difference.

**Comment by paulhocker** [comment]
I closed the issue by accident. At any rate, I used Notepad++ to convert all Tabs to whitespace and that solved the problem. In reading some of the forums etc, it seems that the Editor/Parser does not like mixed Tab/Spaces in the code.

**Comment by QuentinCaffeino** [comment]
> it seems that the Editor/Parser does not like mixed Tab/Spaces in the code.
True.
So if issue is solved I'm going to close it.

**Comment by paulhocker** [comment]
Well, I was able to resolve it by changing the code on my end. Some folks might not figure that out. Is there anyway you can correct this and merge back into master?

**Comment by QuentinCaffeino** [comment]
Well I have spaces everywhere. Maybe you've opened code with godots internal editor or other editor that does auto translation spaces -> tabs?

**Comment by paulhocker** [comment]
Yes, I used Notepad++ to convert the white space to tabs. Would you like me to make a pull request for that?

**Comment by QuentinCaffeino** [comment]
Even tho it works ok if you don't edit files using game editor or mix tabs and spaces, you still want to convert all files to tabs, did I got it right?

**Comment by paulhocker** [comment]
No, I could not actually run a project without fixing the file first. It was just the Console.gd file.

**Comment by QuentinCaffeino** [comment]
Welp, I just tried converting all files and git showed no changes. So could you please try to pull repo again and check?

**Comment by paulhocker** [comment]
Will do.

**Comment by QuentinCaffeino** [comment]
No problem.
Best bud ;)
