### ISSUE TITLE
How to: add_commands

### ISSUE THREAD

**Issue by Gamemap** [quentincaffeino/godot-console#43]
Hi,

you have build a good addon, but sadly I don't understand how to add commands.
Please tell me how to do that.

Thanks,
Gamemap

**Comment by GuillaumeCailhe** [comment]
Hey Gamemap,

The Console can be called from anywhere in your code, so you can do something like :

```gdscript
func_ready():
	Console.add_command('helloworld', self, 'print_hello')\
		.set_description("Say hello.")\
		.register()

func print_hello():
	Console.write_line("Hello world")
```

The first argument of add_command is the name of the command, i.e what you write in the console.
The second and third are the target and the target's name, i.e, the function that is called when the command is typed.
So, in the example above, when you write "helloworld" in the console, this would answer with "Hello world !"
The description is what appears when you use the help command.


You can also add arguments  :
```gdscript
func _ready():
	# 1. argument is command name
	# 2. arg. is target (target could be a funcref)
	# 3. arg. is target name (name is not required if it is the same as first arg or target is a funcref)
	Console.add_command('sayHello', self, 'print_hello')\
		.set_description('Prints "Hello %name%!"')\
		.add_argument('name', TYPE_STRING)\
		.register()

func print_hello(name = ''):
	Console.write_line('Hello ' + name + '!')
```

This is the same example as above but this time, a name argument is set.
So if you write "sayHello Gamemap" in the console, this will print "Hello Gamemap !"

**Comment by quentincaffeino** [comment]
Closing for now as it seems that there's no issue really)

If you'd have any more problems you can reopen this or create new issue.

**Comment by quentincaffeino** [comment]
@all-contributors please add @GuillaumeCailhe for question

**Comment by Gamemap** [comment]
Thank you   <3  
This Addon is fantastic.
