### ISSUE TITLE
const CommandService = preload('Command/CommandService.gd') (cyclic reference error)

### ISSUE THREAD

**Issue by kirai** [quentincaffeino/godot-console#49]
I'm getting a cyclic reference error on line 7 on Console.gd 

![Screen Shot 2021-01-26 at 14 16 06](https://user-images.githubusercontent.com/94629/105803675-50095000-5fe1-11eb-8534-87a9aa3e463e.png)

**Comment by quentincaffeino** [comment]
What godot version are you on?

The easy fix would be to replace preload with load.

**Comment by kirai** [comment]
I'm using (Godot 3.2.2 stable).

If I change with load it seems CommandService.new breaks (I also had to change const with var).

E 0:00:00.538   _load: Failed loading resource: res://Command/CommandService.gd.
  <C++ Error>   Condition "found" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:278 @ _load()
  <Stack Trace> Console.gd:7 @ _init()

![Screen Shot 2021-01-26 at 20 41 01](https://user-images.githubusercontent.com/94629/105840754-df7d2600-6016-11eb-8df6-f7ffdf3d38c8.jpg)

**Comment by quentincaffeino** [comment]
That's odd, I've just tested the version of the console that is on master with latest commit on both 3.2.2 and 3.2.3 and it works. What version of the console are you using and when did you download it?
Also I just saw I forgot to bump the version so I wander if it made godotengine omit latest updates. Could you please try downloading latest release from github? https://github.com/quentincaffeino/godot-console/archive/master.zip

**Comment by kirai** [comment]
I used the latest master and now I'm not having the above problem anymore. 
It works perfectly.
Thank you!
