### ISSUE TITLE
History

### ISSUE THREAD

**Issue by Gamemap** [quentincaffeino/godot-console#52]
Maybe you can write in the documentation that you can change the number of saved previous commands. (`Console.gd` line 30)

Or are there problems if you set the value too high?

Gamemap

**Comment by quentincaffeino** [comment]
Or are there problems if you set the value too high?

I think it isn't a problem, it uses simple `Dictionary`; asides from technical problems if you would to store billions of elements in history. Then it would be a problem since it is stored in memory.

Feel free to open pr, I'll merge it)
