### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by andersmmg** [quentincaffeino/godot-console#54]
As far as I can tell, there's no way to make an argument optional. This would be really nice, and I imagine not too complicated to implement, but I've tried and I don't understand the code well enough

**Comment by quentincaffeino** [comment]
It is optional by default with gdscript. You need to set your argument to null by default.

```gdscript
func test(myarg= null):
  ...
```

Though this doesn't work with C# at the moment.

Which one do you use?

**Comment by andersmmg** [comment]
I'm using GDScript. I had tried to use a command, but it failed because a missing argument. Now it seems to work, it must have been another issue! Now hopefully I can find what that was
