### ISSUE TITLE
Error(7,59): Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended

### ISSUE THREAD

**Issue by keilaoko** [quentincaffeino/godot-console#57]
I'm using the latest version from github, i'm on 3.3.2 Stable, and i'm getting this error message in Console.gd, help would be appreciated
![image](https://user-images.githubusercontent.com/82827754/121754159-e1391900-cae1-11eb-98d1-974c23eaca60.png)

**Comment by quentincaffeino** [comment]
Just pulled `3.3.2-stable` from git and built it, works fine for me. How did you install addon?

**Comment by keilaoko** [comment]
master branch

**Comment by quentincaffeino** [comment]
What?

**Comment by keilaoko** [comment]
i cloned the master branch

**Comment by keilaoko** [comment]
the only branch you have up

**Comment by quentincaffeino** [comment]
Still works for me. Did you follow installation steps in [readme](https://github.com/quentincaffeino/godot-console#installation)?

**Comment by quentincaffeino** [comment]
Closing this as the issue was stale for 2 months
