### ISSUE TITLE
Method 'new' not declared in current class.

### ISSUE THREAD

**Issue by Samuel-Clarke123** [QuentinCaffeino/godot-console#6]
Tried installing the project, but I'm getting an error in Argument.gd->build.
I've added Console.tscn as an autoloaded singleton, but this is still happening.

project.godot included in the zip.

[project.zip](https://github.com/QuentinCaffeino/godot-console/files/3083099/project.zip)

Ver: Godot 3.1 stable

**Comment by QuentinCaffeino** [comment]
Hello,
Thanks for providing demo project for reproducing the issue.
I'm aware of this bug as Godot devs are (see: github.com/godotengine/godot/issues/27491 and github.com/godotengine/godot/issues/19345).
Currently I don't have to much time to fix everything that Godot devs broke with 3.1 version.
Sorry for inconvenience. I'll try to fix this repo during this week. Will keep you updated.
Best

**Comment by jeanlucami** [comment]
Hi, i was able to fix this changing the line:
`return new(name, type) `
with 
`return load("res://path/to/script").new(name, type)` 
both in Argument.gd and accordingly in Command.gd

**Comment by QuentinCaffeino** [comment]
This issue wasn't active for a long time, I'll close it for now. If you will have any other problem don't hesitate to ask.
Best.

**Comment by shayneoneill** [comment]
Can this not be closed? Its still broken.
