### ISSUE TITLE
"Invalid call. Nonexistent function 'getValueIterator' in base 'Reference (CommandCollection.gd)'." when trying to complete command name with Tab

### ISSUE THREAD

**Issue by hilfazer** [quentincaffeino/godot-console#62]
run the project, write 'foo' in the console then press TAB twice
following error occurs
Invalid call. Nonexistent function 'getValueIterator' in base 'Reference (CommandCollection.gd)'.

try same steps but with 'h' written into the console

there is a problem if there are multiple autocomplete options

MRP: https://www.dropbox.com/s/hvnc7vlwp0igle7/ConsoleAutocompleteError.7z?dl=1

**Comment by quentincaffeino** [comment]
Hey hilfazer, thanks for reporting and for perfect MPRs!

@all-contributors please add @hilfazer for bug

**Comment by quentincaffeino** [comment]
I've published a new release v3.2.1, it will take some time till it gets updated on assets though.

**Comment by hilfazer** [comment]
Wow, that was fast. Thanks, @quentincaffeino!
