### ISSUE TITLE
[Feature Request/Question] Is there a system to print back output on console commands without arguments

### ISSUE THREAD

**Issue by MJBrune** [quentincaffeino/godot-console#65]
So my specific use case is say set_winowed or set_max_fps. Both these commands take arguments of what you are setting the max fps to or if the game should be windowed but in typical game consoles, a lot of times by just putting in set_max_fps without an argument the console will print the current max fps without setting it. Currently because of how the callback system works there doesn't seem like there is a good way to get this functionality but perhaps I am missing an obvious way to achieve this result?

Thanks.

**Comment by MJBrune** [comment]
Moments after I posted this I eventually found the command_executed signal which I could simply parse one by one the commands I've created but it's a workaround imho as it will inevitably lead to one large call back trying to parse all my commands which is something the system is already doing.

**Comment by quentincaffeino** [comment]
I could add another signal returning parsed command. Would that solve your problem?
