### ISSUE TITLE
Use theme file to define styles of the controls

### ISSUE THREAD

**Issue by SpyrexDE** [quentincaffeino/godot-console#67]
Using a Console.theme file, that the user is able to edit with ease, would enable every user to adjust the style of the console to fit their game's style. Also, things like increasing the console's font size on bigger screens would get possible. I think it even will save a bit of memory.
Would be a great and relatively easy to do upgrade :)

**Comment by quentincaffeino** [comment]
Sounds interesting however I'm very bad with ui in godot and coming from web godot ui feels very painful. Currently ui wasn't made by me.

If you can help me with that I'll gladly accept a pr.

I'm aware of this problem. Currently this oroject is more of a library, but I plan to make this into a framework which would allow to customize almost anything. See #24
