### ISSUE TITLE
Colored bbcode doesn't work in 3.5.stable anymore

### ISSUE THREAD

**Issue by Dante3085** [quentincaffeino/godot-console#88]
While trying to get an error message to show with red color in the console, I noticed that not even the basic console messages have their yellow color (This is in 3.5.stable):

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/26558776/185803099-304c2842-cded-4538-8b62-fe88d88ce65d.png">

I quickly tested the console in 3.4.4.stable and yes the colors are back. 
So, it seems like 3.5.stable breaks something with bbcode. Probably not just the colors.

**Comment by quentincaffeino** [comment]
Thanks for reporting. I was able to reproduce, but it seems that this is not a console issue so I referenced this issue in godot engine issues.
