### ISSUE TITLE
Add a project icon

### ISSUE THREAD

**Issue by Calinou** [QuentinCaffeino/godot-console#9]
The [asset library page](https://godotengine.org/asset-library/asset/103) currently points to an icon URL that doesn't exist, causing warning messages to be printed in the editor console.

Please add an `icon.png` to this repository to solve the issue :slightly_smiling_face: Its dimensions can be 128×128 (preferably) or 64×64.

**Comment by QuentinCaffeino** [comment]
Hello @Calinou,
Thanks for pointing this out, I've temporary set project screenshot as an icon. I'll try to replace it with a real icon as soon as possible.

Best
