### ISSUE TITLE
Toggling the Console Does Not Work When Multiple InputEvents Occur

### ISSUE THREAD

**Issue by eisclimber** [quentincaffeino/godot-console#95]
When multiple InputEvents occur during one frame and at least one of the `DefaultActions.CONSOLE_TOGGLE`, the console won't open.

As producing additional InputEvents is rather uncommon this might not affect most users but guess fixing this might save someone some time:)

## Expected Behavior
The console should keep open when pressing the toggle key.

## Current Behavior
The console does open but closes after a split-second.

## Possible Solution
Replace [line 94 in `Console.gd`](https://github.com/quentincaffeino/godot-console/blob/32932f916eca461a998808ea6b80817f4f35bff5/addons/quentincaffeino/console/src/Console.gd#L94) with `if e.is_action_pressed(DefaultActions.CONSOLE_TOGGLE):`.  
(`InputEvent.is_action_pressed()` behaves like `Input.is_action_just_pressed()`, just some weird naming I guess...)  

This will check if `e` (the actual InputEvent) is the actual toggle event, instead of just any InputEvent that has been emitted in the same frame as the toggle.

## Steps to Reproduce
1. In A project with the addon installed, create an empty scene and attach a script to it.
2. Add the following code to create an additional InputEvents per frame
```gdscript
func _process(_delta : float) -> void:
	var moving_input = InputEventMouseMotion.new()
	Input.parse_input_event(moving_input)
```
3. Pressing the console-toggle button will produce the behavior as described.

**Comment by quentincaffeino** [comment]
Thanks for reporting, I'll try to find time to fix this. I'm happy to accept a pr if you'd want to do it :)

**Comment by quentincaffeino** [comment]
I couldn't reproduce but the proposed fix totally makes sense
