### ISSUE TITLE
Problem with godot 4 beta 6 in branch godot4

### ISSUE THREAD

**Issue by scriptsengineer** [quentincaffeino/godot-console#99]
When trying to run console.tscn it has ids problems, stating that the console.gd script does not exist
> E 0:00:00:0925   load: res://addons/quentincaffeino/console/src/Console.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://addons/quentincaffeino/console/src/Console.gd
>   <C++ Source>   scene/resources/resource_format_text.cpp:493 @ load()

**Comment by scriptsengineer** [comment]
![image](https://user-images.githubusercontent.com/1673249/204059305-bd4d0c2c-8e12-4799-976b-0d4b092eef40.png)

**Comment by scriptsengineer** [comment]
![image](https://user-images.githubusercontent.com/1673249/204059761-636c9a54-7d9c-43cf-86df-0ad1780274a9.png)

**Comment by quentincaffeino** [comment]
Hello

Tbh I don't remember the state of godot4 branch so it is better to try pr#86 as you already found out.

**Comment by scriptsengineer** [comment]
I couldn't get to the target of the problem, for some reason console.gd is still not found, even though I completely recreated the scene from Console.tscn, my suspicion would be that some code that is used by Console.gd is having problems but the godot does not warn me.

**Comment by scriptsengineer** [comment]
Problem fixed for next beta: https://github.com/godotengine/godot/issues/69177

**Comment by scriptsengineer** [comment]
Working with beta 5 meanwhile.
